name: PlatformIO CI

on:
  push:
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - example: examples/button
            boards: "--board=uno --board=teensy31 --board=due --board=esp32dev"
          - example: examples/drivemode
            boards: "--board=uno --board=teensy31 --board=due --board=esp32dev"
          - example: examples/drivestrength
            boards: "--board=uno --board=teensy31 --board=due --board=esp32dev"
          - example: examples/multiple
            boards: "--board=uno --board=teensy31 --board=due --board=esp32dev"
          - example: examples/readall
            boards: "--board=uno --board=teensy31 --board=due --board=esp32dev"
          - example: examples/softi2c-acewire
            lib-deps: "bxparks/AceWire @ 0.4.1"
            boards: "--board=uno --board=teensy31 --board=due --board=esp32dev"
          - example: examples/softi2c-softwarewire
            lib-deps: "testato/SoftwareWire@1.6.0"
            boards: "--board=uno"
          - example: examples/toggle
            boards: "--board=uno --board=teensy31 --board=due --board=esp32dev"
    steps:
    - uses: actions/checkout@v3
    - uses: actions/cache@v3
      with:
        path: |
          ~/.cache/pip
          ~/.platformio/.cache
        key: ${{ runner.os }}-pio
    - uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    - name: Install PlatformIO Core
      run: pip install --upgrade platformio

    - name: Run PlatformIO
      run: pio ci --lib="." $BOARDS --project-option="lib_deps=$LIB_DEPS"
      env:
        PLATFORMIO_CI_SRC: ${{ matrix.example }}
        BOARDS: ${{ matrix.boards }}
        LIB_DEPS: ${{ matrix.lib-deps }}